// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.AppDbContext;

#nullable disable

namespace Movies.AppDbContext.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    partial class MovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Movies.Entities.Movies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Movies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5336),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 1",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5337),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5339),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 2",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5340),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5341),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 3",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5341),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5342),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 4",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5343),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5344),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 5",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5344),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5345),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 6",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5345),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5346),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 7",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5346),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5347),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 8",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5349),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5349),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 9",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5350),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5351),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 10",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5351),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5352),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 11",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5352),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5354),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 12",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5354),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5355),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 13",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5355),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 14,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5357),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 14",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5358),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 15,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5359),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 15",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5359),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 16,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5360),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 16",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5360),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 17,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5361),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 17",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5362),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 18,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5363),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 18",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5364),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 19,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5364),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 19",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5365),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 20,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5367),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 20",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5367),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 21,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5368),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 21",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5368),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 22,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5369),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 22",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5369),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 23,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5372),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 23",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5372),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 24,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5373),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 24",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5374),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 25,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5375),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 25",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5375),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 26,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5376),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 26",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5377),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 27,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5377),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 27",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5378),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 28,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5380),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 28",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5380),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 29,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5381),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 29",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5381),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 30,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5382),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 30",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5383),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 31,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5383),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 31",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5385),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 32,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5386),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 32",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5386),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 33,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5388),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 33",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5390),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 34,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5391),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 34",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5391),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 35,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5392),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 35",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5393),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 36,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5394),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 36",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5395),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 37,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5396),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 37",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5397),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 38,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5398),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 38",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5398),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 39,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5399),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 39",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5399),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 40,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5401),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 40",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5402),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 41,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5403),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 41",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5403),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 42,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5404),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 42",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5404),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 43,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5405),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 43",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5406),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 44,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5406),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 44",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5407),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 45,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5408),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 45",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5408),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 46,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5409),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 46",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5410),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 47,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5412),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 47",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5413),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 48,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5414),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 48",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5415),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 49,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5416),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 49",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5417),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 50,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5419),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 50",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5419),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 51,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5421),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 51",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5421),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 52,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5422),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 52",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5423),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 53,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5426),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 53",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5427),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 54,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5428),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 54",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5428),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 55,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5431),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 55",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5431),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 56,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5432),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 56",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5433),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 57,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5434),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 57",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5434),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 58,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5435),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 58",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5436),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 59,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5437),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 59",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5438),
                            UpdatedBy = ""
                        },
                        new
                        {
                            Id = 60,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5439),
                            CreatedBy = "",
                            Deleted = false,
                            Images = "https://znews-photo.zingcdn.me/w1920/Uploaded/xbhunku/2019_03_15/D1nkY7UVAAUs7KN.jpg",
                            Likes = 0,
                            Title = "Phim số 60",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5439),
                            UpdatedBy = ""
                        });
                });

            modelBuilder.Entity("Movies.Entities.UserLikeMovies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserLikeMovies", (string)null);
                });

            modelBuilder.Entity("Movies.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5209),
                            CreatedBy = "",
                            Deleted = false,
                            Email = "user@gmail.com",
                            PasswordHash = "$2a$10$8gmvdASPQtXPwQQuwpR66u.VOUvH.E66QUoG8egLGUSzcgfpIZgOG",
                            Updated = new DateTime(2022, 10, 7, 0, 24, 12, 906, DateTimeKind.Local).AddTicks(5222),
                            UpdatedBy = "",
                            UserName = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
